services:
  frontend:
    container_name: web-frontend
    build: ./frontend
    ports:
      - 7860:7860
    volumes:
      - .:/code
    networks:
      - my_network
  backend:
    container_name: web-backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - .:/code
    networks:
      - my_network
  mongodb:
    container_name: web-database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./backend/data/db:/data/db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
